### ISSUE TITLE
play with 百度云

### ISSUE THREAD

**Issue by gldamao** [dirtysalt/tomb#2]
能不能直接关联百度网盘的api 清晰之后直接开播

**Comment by darionyaphet** [comment]
路过 冒个泡   求大师写个read.me ~

**Comment by dirtysalt** [comment]
@darionyaphet 在py/torrent-cleanser里面有个清除torrent里面敏感信息的，这样可以躲避百度云盘的检测。不过话说好久没有去找种子了。
ps: 这个软件可以用来寻找种子。https://github.com/yangyangwithgnu/hardseed，还可以下载到缩略图，真心不错。

**Comment by darionyaphet** [comment]
@dirtysalt  计算机一半是科学 另一半是艺术  在这个repo上得到的充分的体现

**Comment by dirtysalt** [comment]
项目停止开发:)
